"""Updated class messages in db with datetime

Revision ID: a1aaedd434d1
Revises: 49be31ad08df
Create Date: 2022-01-19 02:15:11.657303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1aaedd434d1'
down_revision = '49be31ad08df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('messageid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender', sa.BigInteger(), nullable=False),
    sa.Column('recipient', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('content', sa.String(length=250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recipient'], ['user.id'], ),
    sa.PrimaryKeyConstraint('messageid')
    )
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('messageid', sa.INTEGER(), nullable=False),
    sa.Column('sender', sa.BIGINT(), nullable=False),
    sa.Column('recipient', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('content', sa.VARCHAR(length=250), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['sender'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recipient'], ['user.id'], ),
    sa.PrimaryKeyConstraint('messageid')
    )
    op.drop_table('message')
    # ### end Alembic commands ###
